on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags-ignore:
      - "*"
  pull_request:
  schedule:
    - cron: "16 4 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

name: 💣 Audit 💣

jobs:
  audit-check:
    name: 💣 Audit 💣
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Checkout ✅
        uses: actions/checkout@v4
      - name: 🔄 Update Cargo.lock 🔄
        run: cargo update
      - name: 💵 Rust Cache 💵
        uses: Swatinem/rust-cache@v2
        if: ${{ github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork }}
        with:
          key: ${{ inputs.target }}
          cache-all-crates: true
      - name: 💣 Audit 💣
        uses: rustsec/audit-check@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ignore: "RUSTSEC-2025-0055"